### ISSUE TITLE
Fix Travis post-publish error message

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow-scala-tracker#67]
Each [build](https://travis-ci.org/snowplow/snowplow-scala-tracker/jobs/333182963#L880) with publishing gives this error:

```
[error] java.lang.RuntimeException: failed to sync [secure]/[secure]-scala-tracker@0.5.0 with maven central: {"status":"Sync Failed","messages":"[Failed to close repository: com[secure]analytics-1130. Server response:\n <nexus-error>\n  <errors>\n    <error>\n      <id>*<\u002fid>\n      <msg>Unhandled: Repository: com[secure]analytics-1130 has invalid state: closed<\u002fmsg>\n    <\u002ferror>\n  <\u002ferrors>\n<\u002fnexus-error>, Dropping existing partial staging repository.]"}
[error] 	at scala.sys.package$.error(package.scala:27)
[error] 	at bintray.BintrayRepo.syncMavenCentral(BintrayRepo.scala:153)
[error] 	at bintray.BintrayPlugin$.$anonfun$bintrayPublishSettings$19(BintrayPlugin.scala:111)
[error] 	at bintray.BintrayPlugin$.$anonfun$bintrayPublishSettings$19$adapted(BintrayPlugin.scala:109)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:266)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (*:bintraySyncMavenCentral) failed to sync [secure]/[secure]-scala-tracker@0.5.0 with maven central: {"status":"Sync Failed","messages":"[Failed to close repository: com[secure]analytics-1130. Server response:\n <nexus-error>\n  <errors>\n    <error>\n      <id>*<\u002fid>\n      <msg>Unhandled: Repository: com[secure]analytics-1130 has invalid state: closed<\u002fmsg>\n    <\u002ferror>\n  <\u002ferrors>\n<\u002fnexus-error>, Dropping existing partial staging repository.]"}
```
But artifacts are actually getting published.

I noticed in on few other projects that we're publishing to Bintray.

@BenFradet, have you seen something like this?

**Comment by BenFradet** [comment]
yes, I have, I think it went away on its own after I removed the partial artifacts in bintray which didn't make their way to central iirc

**Comment by chuwy** [comment]
Ok, thanks! Will check if I have any partial artifacts.

**Comment by BenFradet** [comment]
this is a transient issue specific to travis closing
